import type { AuditDefinition } from '@features/enterprise-audit/types/audit';

const LIGHTHOUSE_DOCS = 'https://developer.chrome.com/docs/lighthouse';

function unsupported(
  partial: Omit<
    AuditDefinition,
    'group' | 'supportLevel' | 'unsupportedReason' | 'missingCapability' | 'futureImplementation'
  > & {
    missingCapability: string;
    futureImplementation: string;
    unsupportedReason?: string;
  },
): AuditDefinition {
  return {
    ...partial,
    group: 'C',
    supportLevel: 'unsupported',
    unsupportedReason:
      partial.unsupportedReason ??
      `Unsupported in Extension Environment: ${partial.missingCapability}`,
    fixStrategy: partial.fixStrategy,
  };
}

/** Group C — Lighthouse audits not measurable in MV3 content scripts without CDP/tracing. */
export const UNSUPPORTED_LIGHTHOUSE_AUDITS: AuditDefinition[] = [
  unsupported({
    id: 'speed-index',
    lighthouseId: 'speed-index',
    category: 'performance',
    subcategory: 'metrics',
    title: 'Speed Index',
    description: 'Measures how quickly content is visually displayed.',
    severity: 'High',
    weight: 10,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/speed-index`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Filmstrip trace and visual progress simulation (DevTools trace)',
    futureImplementation: 'Use chrome.debugger CDP Tracing domain or Lighthouse Node runner.',
  }),
  unsupported({
    id: 'interactive',
    lighthouseId: 'interactive',
    category: 'performance',
    subcategory: 'metrics',
    title: 'Time to Interactive',
    description: 'Measures when the page becomes fully interactive.',
    severity: 'High',
    weight: 10,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/interactive`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Main-thread quiet window analysis from full trace',
    futureImplementation: 'Requires Lighthouse trace processor or CDP Performance timeline.',
  }),
  unsupported({
    id: 'unused-javascript',
    lighthouseId: 'unused-javascript',
    category: 'performance',
    subcategory: 'javascript',
    title: 'Reduce unused JavaScript',
    description: 'Detects unused bytes in JavaScript bundles.',
    severity: 'High',
    weight: 8,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/unused-javascript`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'JavaScript Coverage API with execution profiling',
    futureImplementation: 'Use CDP Profiler.takePreciseCoverage or Lighthouse coverage gatherer.',
  }),
  unsupported({
    id: 'unused-css-rules',
    lighthouseId: 'unused-css-rules',
    category: 'performance',
    subcategory: 'css',
    title: 'Reduce unused CSS',
    description: 'Detects unused CSS rules in stylesheets.',
    severity: 'Medium',
    weight: 6,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/unused-css-rules`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'CSS Coverage API',
    futureImplementation: 'Use CDP CSS.startRuleUsageTracking or Lighthouse CSS coverage.',
  }),
  unsupported({
    id: 'unminified-javascript',
    lighthouseId: 'unminified-javascript',
    category: 'performance',
    subcategory: 'javascript',
    title: 'Minify JavaScript',
    description: 'Detects unminified JavaScript payloads.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/unminified-javascript`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Bytecode-level minification detection with savings estimate',
    futureImplementation:
      'Requires network response body analysis via CDP Network.getResponseBody.',
  }),
  unsupported({
    id: 'unminified-css',
    lighthouseId: 'unminified-css',
    category: 'performance',
    subcategory: 'css',
    title: 'Minify CSS',
    description: 'Detects unminified CSS payloads.',
    severity: 'Medium',
    weight: 4,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/unminified-css`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Response body whitespace analysis via privileged network access',
    futureImplementation: 'Use CDP Network.getResponseBody on stylesheet responses.',
  }),
  unsupported({
    id: 'critical-request-chains',
    lighthouseId: 'critical-request-chains',
    category: 'performance',
    subcategory: 'network',
    title: 'Critical request chains',
    description: 'Maps critical dependency chains affecting load.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/critical-request-chains`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Network dependency tree with initiator chain from trace',
    futureImplementation: 'Lighthouse NetworkAnalyzer with full trace initiator graph.',
  }),
  unsupported({
    id: 'mainthread-work-breakdown',
    lighthouseId: 'mainthread-work-breakdown',
    category: 'performance',
    subcategory: 'main-thread',
    title: 'Minimize main-thread work',
    description: 'Breaks down main-thread time by category.',
    severity: 'High',
    weight: 8,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/mainthread-work-breakdown`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Main-thread trace categorization (script, layout, paint)',
    futureImplementation: 'CDP Tracing with Lighthouse main-thread tasks audit.',
  }),
  unsupported({
    id: 'bootup-time',
    lighthouseId: 'bootup-time',
    category: 'performance',
    subcategory: 'javascript',
    title: 'JavaScript bootup time',
    description: 'Measures script parse/compile/execute time per URL.',
    severity: 'High',
    weight: 7,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/bootup-time`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Script evaluation timing per resource from trace',
    futureImplementation: 'Lighthouse bootup-time audit via trace CPU profile.',
  }),
  unsupported({
    id: 'uses-long-cache-ttl',
    lighthouseId: 'uses-long-cache-ttl',
    category: 'network',
    subcategory: 'caching',
    title: 'Serve static assets with efficient cache policy',
    description: 'Validates Cache-Control max-age on static resources.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/uses-long-cache-ttl`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'HTTP response Cache-Control headers (not exposed in Resource Timing)',
    futureImplementation: 'CDP Network.responseReceivedExtraInfo or fetch HEAD with header access.',
  }),
  unsupported({
    id: 'cache-insight',
    lighthouseId: 'cache-insight',
    category: 'network',
    subcategory: 'caching',
    title: 'Cache insight',
    description: 'Analyzes cache lifetime and revalidation behavior.',
    severity: 'Medium',
    weight: 4,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/uses-long-cache-ttl`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Full HTTP cache header inspection',
    futureImplementation: 'CDP Network domain with response headers.',
  }),
  unsupported({
    id: 'errors-in-console',
    lighthouseId: 'errors-in-console',
    category: 'best-practices',
    subcategory: 'console',
    title: 'Browser errors were logged to the console',
    description: 'Detects console.error and uncaught exceptions during load.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/errors-in-console`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Runtime console message capture without page instrumentation before load',
    futureImplementation: 'CDP Runtime.consoleAPICalled listener from navigation start.',
  }),
  unsupported({
    id: 'inspector-issues',
    lighthouseId: 'inspector-issues',
    category: 'best-practices',
    subcategory: 'issues',
    title: 'Issues logged in Chrome Issues panel',
    description: 'Reports Chrome DevTools Issues (CORS, mixed content, etc.).',
    severity: 'Medium',
    weight: 4,
    documentationRef: 'https://developer.chrome.com/docs/devtools/issues',
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'AuditsIssues API (DevTools-only)',
    futureImplementation: 'CDP Audits.getEncodedResponse or Issues panel integration.',
  }),
  unsupported({
    id: 'color-contrast',
    lighthouseId: 'color-contrast',
    category: 'accessibility',
    subcategory: 'contrast',
    title: 'Background and foreground colors have sufficient contrast',
    description: 'Validates WCAG contrast ratios for text nodes.',
    severity: 'High',
    weight: 8,
    documentationRef: `${LIGHTHOUSE_DOCS}/accessibility/color-contrast`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Full computed style tree with overlapping elements and text ranges',
    futureImplementation:
      'Partial DOM sampling implemented separately; full audit needs axe-core in isolated world.',
  }),
  unsupported({
    id: 'bf-cache',
    lighthouseId: 'bf-cache',
    category: 'performance',
    subcategory: 'navigation',
    title: 'Page prevented back/forward cache restoration',
    description: 'Detects bfcache blocking reasons.',
    severity: 'Medium',
    weight: 4,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/bf-cache`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Navigation back/forward simulation with bfcache status',
    futureImplementation: 'Lighthouse bfcache audit with navigation harness.',
  }),
  unsupported({
    id: 'network-requests',
    lighthouseId: 'network-requests',
    category: 'network',
    subcategory: 'diagnostics',
    title: 'Network request waterfall',
    description: 'Full network waterfall with timing phases.',
    severity: 'Info',
    weight: 0,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/network-payloads`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Detailed network waterfall with priority and timing phases',
    futureImplementation: 'CDP Network domain waterfall or HAR export.',
  }),
  unsupported({
    id: 'screenshot-thumbnails',
    lighthouseId: 'screenshot-thumbnails',
    category: 'performance',
    subcategory: 'filmstrip',
    title: 'Screenshot filmstrip',
    description: 'Visual progress screenshots during load.',
    severity: 'Info',
    weight: 0,
    documentationRef: `${LIGHTHOUSE_DOCS}/performance/filmstrip`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Page.captureScreenshot at timed intervals during load',
    futureImplementation: 'CDP Page.captureScreenshot in controlled navigation environment.',
  }),
  unsupported({
    id: 'csp-xss',
    lighthouseId: 'csp-xss',
    category: 'security',
    subcategory: 'csp',
    title: 'Ensure CSP is effective against XSS attacks',
    description: 'Validates Content-Security-Policy strength.',
    severity: 'High',
    weight: 8,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/csp-xss`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Response header CSP analysis with directive evaluation',
    futureImplementation: 'Fetch response headers or CDP Security domain.',
  }),
  unsupported({
    id: 'has-hsts',
    lighthouseId: 'has-hsts',
    category: 'security',
    subcategory: 'transport',
    title: 'Use a strong HSTS policy',
    description: 'Checks Strict-Transport-Security header.',
    severity: 'High',
    weight: 7,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/has-hsts`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'HTTP Strict-Transport-Security response header',
    futureImplementation: 'HEAD request header inspection via extension background fetch.',
  }),
  unsupported({
    id: 'is-origin-isolated',
    lighthouseId: 'is-origin-isolated',
    category: 'security',
    subcategory: 'isolation',
    title: 'Ensure proper origin isolation',
    description: 'Checks COOP/COEP cross-origin isolation.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/is-origin-isolated`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy headers',
    futureImplementation: 'window.crossOriginIsolated + response header validation.',
  }),
  unsupported({
    id: 'clickjacking-mitigation',
    lighthouseId: 'clickjacking-mitigation',
    category: 'security',
    subcategory: 'headers',
    title: 'Mitigate clickjacking with XFO or CSP',
    description: 'Checks X-Frame-Options or frame-ancestors.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/clickjacking-mitigation`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'X-Frame-Options / CSP frame-ancestors response headers',
    futureImplementation: 'Response header fetch from background service worker.',
  }),
  unsupported({
    id: 'trusted-types-xss',
    lighthouseId: 'trusted-types-xss',
    category: 'security',
    subcategory: 'trusted-types',
    title: 'Mitigate DOM-based XSS with Trusted Types',
    description: 'Checks require-trusted-types-for CSP directive.',
    severity: 'Medium',
    weight: 4,
    documentationRef: `${LIGHTHOUSE_DOCS}/best-practices/trusted-types-xss`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'CSP require-trusted-types-for response header analysis',
    futureImplementation: 'Header inspection via fetch/CDP.',
  }),
  unsupported({
    id: 'http-status-code',
    lighthouseId: 'http-status-code',
    category: 'seo',
    subcategory: 'crawlability',
    title: 'Page has successful HTTP status code',
    description: 'Verifies document returns 2xx status.',
    severity: 'High',
    weight: 6,
    documentationRef: `${LIGHTHOUSE_DOCS}/seo/http-status-code`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Document navigation HTTP status from extension content script',
    futureImplementation: 'webRequest or CDP Network.responseReceived for main document.',
  }),
  unsupported({
    id: 'tap-targets',
    lighthouseId: 'tap-targets',
    category: 'seo',
    subcategory: 'mobile',
    title: 'Tap targets are sized appropriately',
    description: 'Validates 48px minimum touch target spacing.',
    severity: 'Medium',
    weight: 5,
    documentationRef: `${LIGHTHOUSE_DOCS}/seo/tap-targets`,
    relatedResources: [],
    fixStrategy: null,
    missingCapability: 'Viewport-scaled bounding box overlap analysis',
    futureImplementation: 'Full geometry audit with mobile emulation.',
  }),
];

export const LIGHTHOUSE_INVENTORY_STATS = {
  unsupportedDefined: UNSUPPORTED_LIGHTHOUSE_AUDITS.length,
};
