export {
  OVERSIZED_IMAGE_RATIO,
  SLOW_RESOURCE_THRESHOLD_MS,
  THIRD_PARTY_PROVIDERS,
  WEB_VITALS_THRESHOLDS,
} from './audit';

export { AUDIT_EXPIRY_MS, AUDIT_TIMEOUT_MS, SESSION_STORAGE_KEY } from './messaging';
export { NAVIGATION_DEBOUNCE_MS, NAVIGATION_TRACK_HASH_CHANGES } from './navigation';
