import { LIGHTHOUSE_DOCS_BASE } from '@features/enterprise-audit/config/thresholds';
import type { RunnableAudit } from '@features/enterprise-audit/types/audit';
import { defineAudit } from '@features/enterprise-audit/utils/auditHelpers';

export const accessibilityAudits: RunnableAudit[] = [
  defineAudit({
    id: 'document-title',
    lighthouseId: 'document-title',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: 'Document has a <title> element',
    description: 'Checks for a non-empty document title.',
    severity: 'High',
    weight: 8,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/document-title`,
    relatedResources: [],
    fixStrategy: 'Add a descriptive <title> element.',
    run({ audit }) {
      const title = audit.metaTags.title?.trim() ?? '';
      const pass = title.length > 0;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: title.length,
        expectedValue: 1,
        threshold: 'non-empty title',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { title: audit.metaTags.title },
      };
    },
  }),
  defineAudit({
    id: 'html-has-lang',
    lighthouseId: 'html-has-lang',
    category: 'accessibility',
    subcategory: 'language',
    title: '<html> element has a [lang] attribute',
    description: 'Ensures the page declares a document language.',
    severity: 'High',
    weight: 8,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/html-has-lang`,
    relatedResources: [],
    fixStrategy: 'Add lang attribute to the <html> element.',
    run({ audit }) {
      const pass = audit.accessibility.hasLangAttribute;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: audit.accessibility.langValue,
        expectedValue: 'valid BCP 47 language',
        threshold: 'lang attribute present',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { lang: audit.accessibility.langValue },
      };
    },
  }),
  defineAudit({
    id: 'image-alt',
    lighthouseId: 'image-alt',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: 'Image elements have [alt] attributes',
    description: 'Detects images missing alt text.',
    severity: 'High',
    weight: 10,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/image-alt`,
    relatedResources: [],
    fixStrategy: 'Add meaningful alt attributes to images.',
    run({ audit }) {
      const count = audit.accessibility.missingAltCount;
      const pass = count === 0;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 images missing alt',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { samples: audit.accessibility.missingAltElements.slice(0, 10) },
      };
    },
  }),
  defineAudit({
    id: 'label',
    lighthouseId: 'label',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: 'Form elements have associated labels',
    description: 'Detects form controls without labels.',
    severity: 'High',
    weight: 8,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/label`,
    relatedResources: [],
    fixStrategy: 'Associate labels with form controls.',
    run({ audit }) {
      const count = audit.accessibility.missingFormLabelsCount;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 unlabeled controls',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { samples: audit.accessibility.missingFormLabelElements.slice(0, 10) },
      };
    },
  }),
  defineAudit({
    id: 'heading-order',
    lighthouseId: 'heading-order',
    category: 'accessibility',
    subcategory: 'navigation',
    title: 'Heading elements appear in sequentially-descending order',
    description: 'Detects skipped heading levels.',
    severity: 'Medium',
    weight: 5,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/heading-order`,
    relatedResources: [],
    fixStrategy: 'Use sequential heading levels without skipping.',
    run({ audit }) {
      const violations = audit.accessibility.headingOrderViolations;
      return {
        status: violations === 0 ? 'pass' : 'fail',
        pass: violations === 0,
        confidence: 'high',
        currentValue: violations,
        expectedValue: 0,
        threshold: '0 heading order violations',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { headingLevels: audit.accessibility.headingLevels },
      };
    },
  }),
  defineAudit({
    id: 'button-name',
    lighthouseId: 'button-name',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: 'Buttons have an accessible name',
    description: 'Detects buttons without discernible text.',
    severity: 'High',
    weight: 7,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/button-name`,
    relatedResources: [],
    fixStrategy: 'Add text or aria-label to buttons.',
    run({ audit }) {
      const count = audit.accessibility.buttonsWithoutName.length;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 unnamed buttons',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { samples: audit.accessibility.buttonsWithoutName },
      };
    },
  }),
  defineAudit({
    id: 'link-name',
    lighthouseId: 'link-name',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: 'Links have a discernible name',
    description: 'Detects links without accessible names.',
    severity: 'High',
    weight: 7,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/link-name`,
    relatedResources: [],
    fixStrategy: 'Add descriptive link text.',
    run({ audit }) {
      const count = audit.accessibility.linksWithoutName.length;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 unnamed links',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { samples: audit.accessibility.linksWithoutName },
      };
    },
  }),
  defineAudit({
    id: 'landmark-one-main',
    lighthouseId: 'landmark-one-main',
    category: 'accessibility',
    subcategory: 'navigation',
    title: 'Document has a main landmark',
    description: 'Checks for a main landmark region.',
    severity: 'Medium',
    weight: 4,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/landmark-one-main`,
    relatedResources: [],
    fixStrategy: 'Add a <main> element or role="main".',
    run({ audit }) {
      const count = audit.accessibility.landmarkMainCount;
      return {
        status: count === 1 ? 'pass' : 'fail',
        pass: count === 1,
        confidence: 'high',
        currentValue: count,
        expectedValue: 1,
        threshold: 'exactly 1 main landmark',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'tabindex',
    lighthouseId: 'tabindex',
    category: 'accessibility',
    subcategory: 'navigation',
    title: 'No element has a [tabindex] > 0',
    description: 'Detects positive tabindex values.',
    severity: 'Medium',
    weight: 4,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/tabindex`,
    relatedResources: [],
    fixStrategy: 'Avoid positive tabindex values.',
    run({ audit }) {
      const count = audit.accessibility.positiveTabIndexCount;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 positive tabindex',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'duplicate-id-aria',
    lighthouseId: 'duplicate-id-aria',
    category: 'accessibility',
    subcategory: 'aria',
    title: 'ARIA IDs are unique',
    description: 'Detects duplicate element IDs.',
    severity: 'Medium',
    weight: 5,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/duplicate-id-aria`,
    relatedResources: [],
    fixStrategy: 'Ensure all id attributes are unique.',
    run({ audit }) {
      const count = audit.accessibility.duplicateIds.length;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 duplicate IDs',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { duplicateIds: audit.accessibility.duplicateIds },
      };
    },
  }),
  defineAudit({
    id: 'frame-title',
    lighthouseId: 'frame-title',
    category: 'accessibility',
    subcategory: 'names-labels',
    title: '<frame> or <iframe> elements have a title',
    description: 'Detects iframes missing title attributes.',
    severity: 'Medium',
    weight: 4,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/accessibility/frame-title`,
    relatedResources: [],
    fixStrategy: 'Add title attributes to iframes.',
    run({ audit }) {
      const count = audit.accessibility.iframeMissingTitle;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 iframes missing title',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
];
