import { LIGHTHOUSE_DOCS_BASE } from '@features/enterprise-audit/config/thresholds';
import type { RunnableAudit } from '@features/enterprise-audit/types/audit';
import { defineAudit } from '@features/enterprise-audit/utils/auditHelpers';

export const bestPracticesAudits: RunnableAudit[] = [
  defineAudit({
    id: 'is-on-https',
    lighthouseId: 'is-on-https',
    category: 'best-practices',
    subcategory: 'security',
    title: 'Uses HTTPS',
    description: 'Checks if the page is served over HTTPS.',
    severity: 'Critical',
    weight: 10,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/is-on-https`,
    relatedResources: [],
    fixStrategy: 'Serve all content over HTTPS.',
    run({ audit }) {
      const pass = audit.security.isHttps;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: audit.security.pageProtocol,
        expectedValue: 'https:',
        threshold: 'HTTPS',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'mixed-content',
    lighthouseId: 'mixed-content',
    category: 'best-practices',
    subcategory: 'security',
    title: 'No mixed content',
    description: 'Detects HTTP resources on HTTPS pages.',
    severity: 'High',
    weight: 8,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/mixed-content`,
    relatedResources: [],
    fixStrategy: 'Upgrade insecure resource URLs to HTTPS.',
    run({ audit }) {
      const count = audit.security.mixedContentCount;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 mixed content URLs',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { urls: audit.security.mixedContentUrls.slice(0, 10) },
      };
    },
  }),
  defineAudit({
    id: 'no-document-write',
    lighthouseId: 'no-document-write',
    category: 'best-practices',
    subcategory: 'javascript',
    title: 'Avoids document.write()',
    description: 'Detects document.write in inline scripts.',
    severity: 'Medium',
    weight: 5,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/no-document-write`,
    relatedResources: [],
    fixStrategy: 'Remove document.write usage.',
    run({ audit }) {
      const pass = !audit.bestPractices.documentWriteUsage;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'medium',
        currentValue: audit.bestPractices.documentWriteUsage,
        expectedValue: false,
        threshold: 'no document.write',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'deprecations',
    lighthouseId: 'deprecations',
    category: 'best-practices',
    subcategory: 'javascript',
    title: 'Avoids deprecated APIs',
    description: 'Scans for known deprecated API strings in scripts.',
    severity: 'Medium',
    weight: 4,
    group: 'B',
    supportLevel: 'partial',
    limitations: ['Static string scan only', 'Cannot detect runtime deprecation warnings'],
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/deprecations`,
    relatedResources: [],
    fixStrategy: 'Replace deprecated APIs with modern alternatives.',
    run({ audit }) {
      const hits = audit.bestPractices.deprecatedApiHits;
      return {
        status: hits.length === 0 ? 'pass' : 'fail',
        pass: hits.length === 0,
        confidence: 'low',
        currentValue: hits.length,
        expectedValue: 0,
        threshold: '0 deprecated API hits',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { hits },
      };
    },
  }),
  defineAudit({
    id: 'charset',
    lighthouseId: 'charset',
    category: 'best-practices',
    subcategory: 'document',
    title: 'Charset declaration',
    description: 'Checks document character encoding.',
    severity: 'Low',
    weight: 2,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/charset`,
    relatedResources: [],
    fixStrategy: 'Declare UTF-8 charset.',
    run({ audit }) {
      const pass = audit.bestPractices.charsetDeclared;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: audit.metaTags.charset,
        expectedValue: 'UTF-8',
        threshold: 'charset declared',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'doctype',
    lighthouseId: 'doctype',
    category: 'best-practices',
    subcategory: 'document',
    title: 'Page has the HTML doctype',
    description: 'Checks for HTML5 doctype.',
    severity: 'Low',
    weight: 2,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/doctype`,
    relatedResources: [],
    fixStrategy: 'Add <!DOCTYPE html>.',
    run({ audit }) {
      const pass = audit.bestPractices.hasDoctype;
      return {
        status: pass ? 'pass' : 'fail',
        pass,
        confidence: 'high',
        currentValue: pass,
        expectedValue: true,
        threshold: 'HTML5 doctype',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'external-anchors-use-rel-noopener',
    lighthouseId: 'external-anchors-use-rel-noopener',
    category: 'best-practices',
    subcategory: 'security',
    title: 'Links to cross-origin destinations are safe',
    description: 'Checks target=_blank links include rel=noopener.',
    severity: 'Medium',
    weight: 4,
    group: 'A',
    supportLevel: 'full',
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/external-anchors-use-rel-noopener`,
    relatedResources: [],
    fixStrategy: 'Add rel="noopener" to target="_blank" links.',
    run({ audit }) {
      const count = audit.bestPractices.targetBlankWithoutNoopener;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'high',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 unsafe target=_blank links',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
  defineAudit({
    id: 'js-libraries',
    lighthouseId: 'js-libraries',
    category: 'best-practices',
    subcategory: 'javascript',
    title: 'Detected JavaScript libraries',
    description: 'Reports detected third-party JS libraries.',
    severity: 'Info',
    weight: 0,
    group: 'B',
    supportLevel: 'partial',
    limitations: ['URL pattern matching only'],
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/js-libraries`,
    relatedResources: [],
    fixStrategy: null,
    run({ audit }) {
      return {
        status: 'pass',
        pass: true,
        confidence: 'low',
        currentValue: audit.bestPractices.detectedLibraries.length,
        expectedValue: null,
        threshold: null,
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: { libraries: audit.bestPractices.detectedLibraries },
      };
    },
  }),
  defineAudit({
    id: 'image-aspect-ratio',
    lighthouseId: 'image-aspect-ratio',
    category: 'best-practices',
    subcategory: 'images',
    title: 'Displays images with correct aspect ratio',
    description: 'Detects images missing width/height attributes.',
    severity: 'Medium',
    weight: 4,
    group: 'B',
    supportLevel: 'partial',
    limitations: ['Cannot compare rendered vs intrinsic ratio'],
    documentationRef: `${LIGHTHOUSE_DOCS_BASE}/best-practices/image-aspect-ratio`,
    relatedResources: [],
    fixStrategy: 'Set width and height attributes on images.',
    run({ audit }) {
      const count = audit.images.missingDimensionsCount;
      return {
        status: count === 0 ? 'pass' : 'fail',
        pass: count === 0,
        confidence: 'medium',
        currentValue: count,
        expectedValue: 0,
        threshold: '0 images missing dimensions',
        unsupportedReason: null,
        missingCapability: null,
        futureImplementation: null,
        evidence: {},
      };
    },
  }),
];
